on:
  release:
    types:
      - published

  workflow_dispatch:


jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: celsiusnarhwal/poetry-publish@v2
        name: Publish Package
        with:
          python-version: 3.11.1
          poetry-version: 1.3.1
          build: true
          token: ${{ secrets.PYPI_TOKEN }}